-- MySQL Script generated by MySQL Workbench
-- Sat Jan  4 21:41:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cashback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cashback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cashback` DEFAULT CHARACTER SET utf8 ;
USE `cashback` ;

-- -----------------------------------------------------
-- Table `cashback`.`revendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cashback`.`revendedor` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(60) NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(45) NULL,
  `data_cadastro` TIMESTAMP NULL,
  `data_atualizacao` TIMESTAMP NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cashback`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cashback`.`compra` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `valor` DECIMAL(10,2) NULL,
  `porcentagem` INT NULL,
  `status` SMALLINT NULL COMMENT '0 - Em validação\n1 - Aprovado',
  `data_compra` DATE NULL,
  `data_atualizacao` TIMESTAMP NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_compra_revendedor_idx` (`cpf` ASC),
  CONSTRAINT `fk_compra_revendedor`
    FOREIGN KEY (`cpf`)
    REFERENCES `cashback`.`revendedor` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
